version: 2
project_name: yummy
before:
  hooks:
    - go mod tidy
    - go test ./...
    - go clean -cache
    - rm -rf dist/

builds:
  - id: yummy
    binary: yummy
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/GarroshIcecream/yummy/internal/version.Version={{.Version}}
      - -X github.com/GarroshIcecream/yummy/internal/version.BuildTime={{.CommitTimestamp}}
      - -X github.com/GarroshIcecream/yummy/internal/version.GitCommit={{.FullCommit}}
    flags:
      - -trimpath
      - -buildvcs=true
    tags:
      - netgo
    env:
      - CGO_ENABLED=0

archives:
  - id: yummy-archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
      - goos: linux
        formats: [tar.gz]
      - goos: darwin
        formats: [tar.gz]
    files:
      - assets/yummy_logo.svg
      - readme.md
      - LICENSE
    formats: [tar.gz]

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  github:
    owner: GarroshIcecream
    name: yummy

  header: |
    ## 🍳 Yummy Recipe Manager {{ .Version }}

    A terminal-based cookbook manager and recipe assistant built with Go and Bubble Tea.

    ### What's New
    - Check the changelog for detailed changes

    ### Installation
    Download the appropriate binary for your platform and extract it to a directory in your PATH.

  footer: |
    ### Support
    - Report issues: [GitHub Issues](https://github.com/GarroshIcecream/yummy/issues)
    - Documentation: [README](https://github.com/GarroshIcecream/yummy#readme)

    ### Development
    Built with ❤️ using Go and [Bubble Tea](https://github.com/charmbracelet/bubbletea)

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - '^chore:'

# Homebrew cask (tap) - v2 uses homebrew_casks
homebrew_casks:
  - name: yummy
    binaries: [yummy]
    repository:
      owner: GarroshIcecream
      name: homebrew-yummy
      branch: main
    homepage: "https://github.com/GarroshIcecream/yummy"
    description: "Terminal-based cookbook manager and recipe assistant"
    license: "MIT"
    skip_upload: auto
    caveats: "Yummy is a terminal-based application. Run 'yummy --help' to get started."
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yummy"]
          end

# Scoop manifest (optional)
scoops:
  - name: yummy
    description: "Terminal-based cookbook manager and recipe assistant"
    homepage: "https://github.com/GarroshIcecream/yummy"
    license: "MIT"
    skip_upload: auto
    # Persist data directory
    persist:
      - ".yummy"

# Docker configuration (v2: uses pre-built binaries from GoReleaser context)
dockers_v2:
  - id: yummy-docker
    ids: [yummy]
    dockerfile: Dockerfile.goreleaser
    images:
      - "ghcr.io/garroshicecream/yummy"
    tags:
      - "{{ .Version }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "Terminal-based cookbook manager and recipe assistant"
      "org.opencontainers.image.source": "https://github.com/GarroshIcecream/yummy"

# Metadata
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
