package recipe

var corpusMeasures = []string{
	"tablespoon",
	"tablespoons",
	"milliliter",
	"teaspoon",
	"teaspoons",
	"milliliter",
	"pints",
	"pound",
	"pounds",
	"quart",
	"quarts",
	"gram",
	"grams",
	"ounce",
	"ounces",
	"tsp",
	"tsps",
	"tbl",
	"tbls",
	"tblsp",
	"tbs",
	"tbsp",
	"tbsps",
	"clove",
	"cloves",
	"can",
	"cans",
	"canned",
	"cup",
	"cups",
	"ml",
	"oz",
	"c",
	"g",
	"oz",
	"t",
	"c",
	"g",
	"t",
}

var corpusMeasuresMap = map[string]string{
	"c":           "cup",
	"can":         "can",
	"canned":      "can",
	"cans":        "can",
	"cup":         "cup",
	"cups":        "cup",
	"g":           "gram",
	"gram":        "gram",
	"grams":       "gram",
	"milliliter":  "milliliter",
	"ml":          "milliliter",
	"ounce":       "ounce",
	"ounces":      "ounce",
	"oz":          "ounce",
	"pint":        "pint",
	"pints":       "pint",
	"pound":       "pound",
	"pounds":      "pound",
	"quart":       "quart",
	"quarts":      "quart",
	"t":           "tsp",
	"tablespoon":  "tbl",
	"tablespoons": "tbl",
	"tbl":         "tbl",
	"tbls":        "tbl",
	"tblsp":       "tbl",
	"tbs":         "tbl",
	"tbsp":        "tbl",
	"tbsps":       "tbl",
	"teaspoon":    "tsp",
	"teaspoons":   "tsp",
	"tsp":         "tsp",
	"tsps":        "tsp",
}
